version: '3'
services:
  rdb:
    image: mysql:8.0.33
    restart: always
    ports:
      - 13301:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nerdy_db

  redis:
    image: redis:alpine
    container_name: nerdy_redis
    command: redis-server --requirepass mypassword --port 6379
    hostname: redis
    ports:
      - 13401:6379